vich_uploader:
    db_driver: orm

    mappings:
        vehicle_image:
            uri_prefix: /uploads/vehicles
            upload_destination: '%kernel.project_dir%/public/uploads/vehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false
